const express = require("express");
const cors = require("cors");
const bodyParser = require("body-parser");
require("dotenv").config({ path: "./config/.env" });
require("./config/db");
const productsRouter = require("./routes/productsRouter");
const categoryRouter = require("./routes/categoryRouter");
const sliderRouter = require("./routes/sliderRouter");
const userRouter = require("./routes/userRouter");
const orderRouter = require("./routes/orderRouter");
const app = express();
app.use(express.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(cors());
app.use("/api/products", productsRouter);
app.use("/api/category", categoryRouter);
app.use("/api/slider", sliderRouter);
app.use("/api/users", userRouter);
app.use("/api/orders", orderRouter);
const port = process.env.PORT;
app.listen(port, console.log(`Server Running On Port ${port}`));
